### ISSUE TITLE
DDoS attacts during the mainnet launch

### ISSUE THREAD

**Issue by ramtej** [eoscanada/eos-bios#19]
Hi Alex, 

we are currently hardening our infrastructure and have done some DDoS tests. With  very simple tools, like https://code.google.com/p/slowhttptest/ we can kill the exposed EOS-BIOS endpoints, e.g. http://stage12.testnets.eoscanada.com/ within seconds. Since the disco-file contains all the known BPC - and their endpoints, one can easily at least postpone the whole mainnet launch.

wget http://stage12.testnets.eoscanada.com/ 
HTTP request sent, awaiting response... 500 Internal Server Error
**2018-05-27 10:24:17 ERROR 500: Internal Server Error.**

We need to solve that. From my perspective we can be sure, that they will be DDoS attacts during the launch.  

Regards, 
JJ (EOS Germany)

**Comment by abourget** [comment]
This is only one endpoint. There are other endpoints in the network (like http://stage13.eosn.io:8888 ) and yes this one is a testnet endpoint, directly exposed to the Internet.  As we go towards mainnet, everyone needs to increase their capacity and make their setup more "mainnet-like", for a stable launch.

http://stage12.testnets.eoscanada.com  is not an EOS-BIOS endpoint, it's a small program I wrote to simplify calls to the blockchain directly.

What doesn't kill us makes us stronger.. killing the previous stages will actually provide good practice for BPs involved.

**Comment by ramtej** [comment]
Hi Alex, 

agree, there are the http and p2p ports. I have still the impression that we need to do more in order to hardening the EOS infrastructure for the mainnet launch.  

> What doesn't kill us makes us stronger..

Well, yes.. somehow.. :-)

Regards, 
jj

**Comment by niclash** [comment]
So, in principle, all BPs *should* have their own seed network running and blocked off the public internet, right? Perhaps should stress that more in the next couple of days...

**Comment by abourget** [comment]
We need a strong swarm of diversified stage network nodes. Just like mainnet. There's nowhere to hide :)

Can I close this @ramtej ?

**Comment by ramtej** [comment]
Due to the actual discussion, let's close it AND canalize the efforts to practical working instructions, how to secure the launch and in general the EOS Blockchain. 

Thank you Alex!
