### ISSUE TITLE
run " ./eos-bios orchestrate" ERROR

### ISSUE THREAD

**Issue by GiggleAll** [eoscanada/eos-bios#21]
![image](https://user-images.githubusercontent.com/12868931/40614691-7b5f022a-62b6-11e8-92fb-64bbd255fb19.png)

version:0.9.5
location: china

Does the reason network?

If you have time, please give me some advice.

**Comment by abourget** [comment]
The default endpoint is `https://ipfs.io`, you can set a different gateway nearby with `--ipfs`.

You can even run your own `ipfs daemon --init`.. and use `--ipfs http://localhost:8080` 

Once it goes through, it's cached and you're good to go.
