### ISSUE TITLE
about "./eos-bios boot" doubt

### ISSUE THREAD

**Issue by GiggleAll** [eoscanada/eos-bios#22]
![image](https://user-images.githubusercontent.com/12868931/40638698-5b7b8526-633f-11e8-88dd-161237475f61.png)

When I run "./eos-bios boot" command ,have this problem. I don't known why.   This is bad? or some other situation?  
If you have time, please give me some advice.

Thanks,
zhangzc

**Comment by eosauthority** [comment]
Did you try the following?
./eos-bios boot --single

**Comment by GiggleAll** [comment]
thanks, I will try it.

**Comment by abourget** [comment]
This means it's trying to reach your `target_http_address` and it can't reach it. Could mean you haven't started your node, it's not listening, that address doesn't resolve, isn't valid, etc.. check `output.log` which contains more details.

The channel is a more lively place to ask for help, you'll see :)
