### ISSUE TITLE
Files on IPFS seem to be unreachable

### ISSUE THREAD

**Issue by nanmu42** [eoscanada/eos-bios#29]
Some files of eos-bios are hosted on IPFS:

https://github.com/eoscanada/eos-bios/blob/68d70f6dfe8d1f5612fb7a603bffffd225a21f0b/sample_config/my_discovery_file.yaml#L51-L104

Unfortunately, following files seem to be unreachable:

```
Downloading and caching content from IPFS: "/ipfs/QmSit9SXVBjd5oAKxFzT9hwMUwDS5njdb4wihxRNmw5JQn"
Downloading and caching content from IPFS: "/ipfs/QmaEBLxhP7Ea7xUAKPVaabw3zDzKY4qrfD5hfdmggDnPrL"
Downloading and caching content from IPFS: "/ipfs/QmP51RGzn2q9q1QX9rqVnKJ2DaQUG55AMD8FamoSuy6AET"
Downloading and caching content from IPFS: "/ipfs/QmXsZX3LVnisnDoaVYCK215fQorDcnjJpx5XDaBppzeERQ"
Downloading and caching content from IPFS: "/ipfs/QmRiWnFsamUB3rWsnUVEekjLxPH3JrCjXfFQ4hEPkiGBrk"
```

```
fetch network: downloading content: content "eosio.system.abi": couldn't get https://ipfs.io/ipfs/QmP51RGzn2q9q1QX9rqVnKJ2DaQUG55AMD8FamoSuy6AET, return code: 504, server error: "<html>\
r\n<head><title>504 Gateway Time-out</title><"
```

Is there a way to fix this?
Fabulous work! Thank you. :beers:

**Comment by abourget** [comment]
Is this still true ? Seed nodes should serve the content now..

**Comment by nanmu42** [comment]
All are good, except `/ipfs/QmaEBLxhP7Ea7xUAKPVaabw3zDzKY4qrfD5hfdmggDnPrL`.

Resovled by downloading it directly from `https://github.com/eosauthority/genesis/blob/master/snapshot-files/final/2/snapshot.csv` and puting it in `~/.eos-bios-cache`.

Thank you. :notes:
